import React, { useState } from "react";
import "./App.css";
import MovieList from "../components/MovieList";

const App: React.FC = () => {
  const [movies] = useState([
    {
      id: 1,
      title: "Proyecto Atlas",
      gender: "Ciencia Ficción",
      image: "Atlas.jpg",
      description: "Un ambicioso proyecto científico que cambia el futuro.",
      rating: 8.2,
      duration: 135,
      releaseYear: "Noviembre", 
      director: "John Doe",
    },
    {
      id: 2,
      title: "Beekepper",
      gender: "Acción",
      image: "beek.jpg",
      description: "Un héroe anónimo lucha por la justicia.",
      rating: 7.5,
      duration: 120,
      releaseYear: "Octubre",
      director: "Jane Smith",
    },
    {
      id: 3,
      title: "Beetlejuice",
      gender: "Acción",
      image: "Beetlejuice.jpg",
      description: "Un thriller sobrenatural lleno de giros inesperados.",
      rating: 8.0,
      duration: 130,
      releaseYear: "Diciembre",
      director: "Tim Burton",
    },
    {
      id: 4,
      title: "Deadpool",
      gender: "Acción y comedia",
      image: "deap.jpg",
      description: "El antihéroe más sarcástico del universo Marvel.",
      rating: 8.5,
      duration: 109,
      director: "David Leitch",
    },
    {
      id: 5,
      title: "El cuervo",
      gender: "Drama",
      image: "El_cuervo.jpg",
      description: "Una historia de redención y venganza.",
      rating: 7.9,
      duration: 102,
      releaseYear: "Octubre",
      director: "Alex Proyas",
    },
    {
      id: 6,
      title: "El Especialista",
      gender: "Drama",
      image: "el-especialist.jpg",
      description: "Un maestro en su oficio enfrenta retos inesperados.",
      rating: 7.3,
      duration: 115,
      releaseYear: "Octubre",
      director: "Luis García",
    },
    {
      id: 7,
      title: "Intensamente II",
      gender: "Infantil",
      image: "elmen.jpg",
      description: "Las emociones vuelven con más aventuras y risas.",
      rating: 8.7,
      releaseYear: "Septiembre",
      duration: 95,
      director: "Pete Docter",
    },
    {
      id: 8,
      title: "Red Right Hand",
      gender: "Acción",
      image: "red.jpg",
      description: "Una historia de justicia y redención en un mundo oscuro.",
      rating: 7.8,
      duration: 118,
      releaseYear: "Diciembre",
      director: "Mark Harris",
    },
    {
      id: 9,
      title: "El planeta de los simios",
      gender: "Drama y Acción",
      image: "simios.jpg",
      description: "Una épica batalla entre humanos y simios por el planeta.",
      rating: 8.3,
      duration: 140,
      releaseYear: "Octubre",
      director: "Matt Reeves",
    },
  ]);
export default App;
